#!/usr/bin/python

import Adafruit_CharLCD as LCD
import sys

# Raspberry Pi pin setup
lcd_rs = 16
lcd_en = 26
lcd_d4 = 12
lcd_d5 = 17
lcd_d6 = 18
lcd_d7 = 27
lcd_backlight = 2

# Define LCD column and row size for 16x2 LCD.
lcd_columns = 16
lcd_rows = 2

lcd = LCD.Adafruit_CharLCD(lcd_rs, lcd_en, lcd_d4, lcd_d5, lcd_d6, lcd_d7, lcd_columns, lcd_rows, lcd_backlight)

lcd.message(sys.argv[1])
